export { default as Login} from './login'
export { default as CreateProfile} from './profile'
export { default as Dashboard} from './dashboard'
export { default as Home} from './home'
export { default as Account} from './account'