export { default as Login} from './login'
export { default as Logout} from './logout'
export { default as CreateProfile} from './profile'
export { default as Dashboard} from './dashboard'
export { default as Home} from './home'